FROM golang:1.24-alpine AS builder
RUN apk add --no-cache ffmpeg
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o blur-worker ./services/ai-worker/blur.go

FROM alpine:latest
RUN apk add --no-cache ffmpeg
WORKDIR /root/
COPY --from=builder /app/blur-worker .
CMD ["./blur-worker"]
