apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "evms.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.recordings.storageClass }}
  resources:
    requests:
      storage: {{ .Values.recordings.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thumbnail-cache-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "evms.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.thumbnailCache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.thumbnailCache.size }}
