apiVersion: v1
kind: Secret
metadata:
  name: evms-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  db-url: {{ .Values.db.url | quote }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
  db-password: {{ .Values.db.password | quote }}
