{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: evms-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "evms.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.db.url }}
  db-url: {{ .Values.db.url | quote }}
{{- end }}
{{- if .Values.jwt.secret }}
  jwt-secret: {{ .Values.jwt.secret | quote }}
{{- end }}
{{- if .Values.db.password }}
  db-password: {{ .Values.db.password | quote }}
{{- end }}
{{- end }}
