export const AUTH_ROUTES = {
  LOGIN: '/auth/login',
  CALLBACK: '/auth/callback',
  LOGOUT: '/auth/logout',
  REFRESH: '/auth/refresh',
  CSRF: '/auth/csrf',
  MFA_ENROLL: '/auth/mfa/enroll',
  MFA_VERIFY: '/auth/mfa/verify',
  MFA_STATUS: '/auth/mfa/status',
  MFA_RECOVERY: '/auth/mfa/recovery',
  PASSWORD_CHANGE: '/auth/password/change',
  PASSWORD_POLICY: '/auth/password/policy',
  SESSIONS: '/auth/sessions',
  SESSION_REVOKE: '/auth/sessions/revoke',
  SESSION_REVOKE_ALL: '/auth/sessions/revoke-all',
  API_KEYS: '/auth/api-keys',
  API_KEY_REVOKE: '/auth/api-keys/revoke',
  SSO_PROVIDERS: '/auth/sso/providers',
  SSO_LOGIN: '/auth/sso/login',
  SSO_CALLBACK: '/auth/sso/callback',
  SCOPES: {
    VIEW: 'view',
    EDIT: 'edit',
    ADMIN: 'admin',
  },
} as const;
